export const GENERATION_COVERS = [
  [
    require('../data/gen/i/en/blue.png'),
    require('../data/gen/i/en/red.png'),
    require('../data/gen/i/en/yellow.png'),
  ],
  [
    require('../data/gen/ii/en/crystal.png'),
    require('../data/gen/ii/en/gold.png'),
    require('../data/gen/ii/en/silver.png'),
  ],
  [
    require('../data/gen/iii/en/emerald.png'),
    require('../data/gen/iii/en/firered.png'),
    require('../data/gen/iii/en/leafgreen.png'),
    require('../data/gen/iii/en/ruby.png'),
    require('../data/gen/iii/en/sapphire.png'),
  ],
  [
    require('../data/gen/iv/en/diamond.png'),
    require('../data/gen/iv/en/heartgold.png'),
    require('../data/gen/iv/en/pearl.png'),
    require('../data/gen/iv/en/platinum.png'),
    require('../data/gen/iv/en/soulsilver.png'),
  ],
  [
    require('../data/gen/v/en/black.png'),
    require('../data/gen/v/en/black2.png'),
    require('../data/gen/v/en/white.png'),
    require('../data/gen/v/en/white2.png'),
  ],
  [
    require('../data/gen/vi/en/alphasapphire.png'),
    require('../data/gen/vi/en/omegaruby.png'),
    require('../data/gen/vi/en/x.png'),
    require('../data/gen/vi/en/y.png'),
  ],
  [
    require('../data/gen/vii/en/letsgoeevee.png'),
    require('../data/gen/vii/en/letsgopikachu.png'),
    require('../data/gen/vii/en/moon.png'),
    require('../data/gen/vii/en/sun.png'),
    require('../data/gen/vii/en/ultramoon.png'),
    require('../data/gen/vii/en/ultrasun.png'),
  ],
  [
    require('../data/gen/viii/en/brilliantdiamond.png'),
    require('../data/gen/viii/en/legendsarceus.png'),
    require('../data/gen/viii/en/shield.png'),
    require('../data/gen/viii/en/shiningpearl.png'),
    require('../data/gen/viii/en/sword.png'),
  ],
  [
    require('../data/gen/ix/en/scarlet.png'),
    require('../data/gen/ix/en/violet.png'),
    require('../data/gen/ix/en/legendsza.png'),
  ],
];
